# Generated by Django 5.0.6 on 2024-06-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="product_name",
                        db_index=True,
                        max_length=250,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_column="product_category",
                        db_index=True,
                        max_length=250,
                        verbose_name="Category",
                    ),
                ),
                (
                    "price",
                    models.FloatField(db_column="product_price", verbose_name="Price"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="creation_date_time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updation_date_time"),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
    ]
