# Generated by Django 5.0.6 on 2024-06-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(
                db_column="price_currency",
                default="INR",
                max_length=10,
                verbose_name="Currency",
            ),
        ),
    ]
